export const springConfig = {
    default: {
        tension: 20,
        mass: 1,
        friction: 5,
        velocity: 0,
        precision: 0.01,
    },
    linearFast: {
        tension: 300,
        mass: 0.1,
        friction: 26,
        velocity: 0,
        precision: 0.1,
    },
    linearMedium: {
        tension: 150,
        mass: 0.1,
        friction: 26,
        velocity: 0,
        precision: 0.1,
    },
    linearSlow: {
        tension: 80,
        mass: 0.1,
        friction: 26,
        velocity: 0,
        precision: 0.1,
    },
    gentle: {
        tension: 120,
        mass: 1,
        friction: 14,
        velocity: 0,
        precision: 0.01,
    },
    wobbly: {
        tension: 180,
        mass: 1,
        friction: 12,
        velocity: 0,
        precision: 0.01,
    },
    bounce: {
        tension: 200,
        mass: 3,
        friction: 5,
        velocity: 0,
        precision: 0.01,
    },
};
