set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set mouse=a
set autoindent
set colorcolumn=80
set signcolumn=yes
set guicursor=
set relativenumber
set nowrap
set incsearch
set scrolloff=8
set nohlsearch
set belloff=all
syntax on

let g:netrw_banner=0
let g:vim_json_conceal=0
